# Load necessary R-Packages
library(dplyr)
library(ggplot2)
library(ggrepel)
library(mrbin)
library(purrr)
library(tidyr)
library(scales)

# 1. Plot a spectral section with optional marking of picked Signal ------

# This function plots a selected subregion of a J-resolved NMR spectrum.
# It can optionally mark picked signals and their base areas.

# Necessary input:
# sub_spectrum:       A dataframe containing the subregion of the J-resolved spectrum.
#                     This is typically generated by a preceding signal identification step.

# Optional inputs:
# sampleID:           ID-number of the examined sample, used for the plot title (Default: "NA").
# analyte:            Name of the examined compound, used for the plot title (Default: "NA").
# mark_signal:        Logical, turns the marking of picked signals on and off (TRUE = On, FALSE = Off; Default: FALSE).
# mark_signal_data:   Dataframe containing the picked signal information, used if mark_signal is TRUE.
#                     Expected to be part of the output result_list from a signal identification procedure.
# mark_color:         Color for signal markings and information labels (Default: "red").
# mark_rel_x_shift:   Defines the relative horizontal offset for signal information labels (Default: 0.05 = 5% of F2 range).
# mark_base_area:     Logical, turns the marking of signal base areas on and off (TRUE = On, FALSE = Off; Default: FALSE).
# base_area_data:     Dataframe generated by the center of mass function calculate_CoM(), used if mark_base_area is TRUE.
#                     Expected to be part of the output list from a base area calculation.
# base_area_color:    Color for the base area tiles (Default: "blue").
# base_area_alpha:    Transparency level for the base area tiles (Default: 0.2).
# minor_subdivisions: The exact number of minor breaks to be placed between each pair of major breaks.
#                     E.g., 1 for one midpoint minor tick, 2 for two evenly spaced minor ticks. (Default: 1)

JRES_plot_spectrum <- function(sub_spectrum,
                               sampleID = "NA",
                               analyte = "NA",
                               mark_signal = FALSE,
                               mark_signal_data = NULL,
                               mark_color = "red",
                               mark_rel_x_shift = 0.05,
                               mark_base_area = FALSE,
                               base_area_data = NULL,
                               base_area_color = "blue",
                               base_area_alpha = 0.2,
                               minor_subdivisions = 1
) {
  
  # Helper function to create a specified number of evenly spaced minor breaks between major breaks.
  # num_breaks_between specifies the exact number of minor breaks to be inserted.
  create_evenly_spaced_minor_breaks <- function(major_breaks, num_breaks_between) {
    if (length(major_breaks) < 2 || num_breaks_between <= 0) {
      return(NULL) # No minor breaks if less than 2 major breaks or 0 breaks requested
    }
    minor_breaks <- c()
    for (i in 1:(length(major_breaks) - 1)) {
      start <- major_breaks[i]
      end <- major_breaks[i+1]
      # Generate points: num_breaks_between + 2 points to include start and end,
      # then remove start and end to get only the intermediate points.
      new_breaks <- seq(start, end, length.out = num_breaks_between + 2)
      minor_breaks <- c(minor_breaks, new_breaks[-c(1, length(new_breaks))])
    }
    return(unique(minor_breaks)) # Use unique to handle potential floating point duplicates
  }
  
  # Convert the spectrum to a long format, which is necessary for ggplot2.
  sub_spectrum_long <- sub_spectrum %>%
    pivot_longer(cols = everything(),
                 names_to = "F2ppm_char", # Temporary name for F2ppm, initially as character
                 values_to = "Intensity") %>%
    mutate(F1ppm_char = rep(rownames(sub_spectrum), each = ncol(sub_spectrum)))
  
  # Convert character F1ppm and F2ppm columns to numeric.
  sub_spectrum_long$F1ppm <- as.numeric(as.character(sub_spectrum_long$F1ppm_char))
  sub_spectrum_long$F2ppm <- as.numeric(as.character(sub_spectrum_long$F2ppm_char))
  
  # Remove the temporary character columns to clean up the dataframe.
  sub_spectrum_long <- sub_spectrum_long %>% select(-F1ppm_char, -F2ppm_char)
  
  # Determine the boundaries of the plot for drawing the outer frame.
  plot_xmin <- min(sub_spectrum_long$F2ppm)
  plot_xmax <- max(sub_spectrum_long$F2ppm)
  plot_ymin <- min(sub_spectrum_long$F1ppm)
  plot_ymax <- max(sub_spectrum_long$F1ppm)
  
  # Calculate resolution (step size) for geom_tile based on the main spectrum data.
  f2_unique_values <- sort(unique(sub_spectrum_long$F2ppm))
  f2_resolution <- ifelse(length(f2_unique_values) > 1, min(diff(f2_unique_values)), 0.001)
  
  f1_unique_values <- sort(unique(sub_spectrum_long$F1ppm))
  f1_resolution <- ifelse(length(f1_unique_values) > 1, min(diff(f1_unique_values)), 0.01)
  
  # Calculate major breaks for F2 and F1 axes.
  f2_major_breaks <- scales::pretty_breaks(n = 5)(sub_spectrum_long$F2ppm)
  f1_major_breaks <- scales::pretty_breaks(n = 7)(sub_spectrum_long$F1ppm)
  
  # Generate minor breaks using the custom helper function, based on the requested number of breaks.
  f2_minor_breaks <- create_evenly_spaced_minor_breaks(f2_major_breaks, minor_subdivisions)
  f1_minor_breaks <- create_evenly_spaced_minor_breaks(f1_major_breaks, minor_subdivisions)
  
  # Create the base plot of the spectral region using ggplot2.
  p <- ggplot(sub_spectrum_long, aes(x = F2ppm, y = F1ppm, z = Intensity)) +
    geom_contour_filled(aes(fill = after_stat(level)), show.legend = FALSE) +
    geom_contour(color = "black", linewidth = 0.2) +
    scale_fill_grey(start = 1, end = 0) +
    labs(
      title = paste(sampleID, analyte, "J-resolved", sep = "_"),
      x = "F2 [ppm]",
      y = "F1 [ppm]"
    ) +
    theme_minimal() +
    annotate(
      "rect",
      xmin = plot_xmin, xmax = plot_xmax, ymin = plot_ymin, ymax = plot_ymax,
      fill = NA,
      color = "black",
      linewidth = 0.5
    ) +
    # Use the calculated major and minor breaks for the F2 axis.
    scale_x_reverse(
      expand = c(0, 0),
      breaks = f2_major_breaks,
      minor_breaks = f2_minor_breaks,
      guide = guide_axis(minor.ticks = TRUE)
    ) +
    # Use the calculated major and minor breaks for the F1 axis.
    scale_y_reverse(
      expand = c(0, 0),
      breaks = f1_major_breaks,
      minor_breaks = f1_minor_breaks,
      guide = guide_axis(minor.ticks = TRUE)
    ) +
    theme(
      panel.grid = element_blank(),
      legend.background = element_rect(fill = "white"),
      axis.line = element_line(color = "black"),
      axis.ticks = element_line(color = "black"),
      axis.text = element_text(size = 10),
      axis.title = element_text(size = 12)
    )
  
  # Optional: Plot the base area of the peaks if `mark_base_area` is TRUE and data is provided.
  if (isTRUE(mark_base_area) && !is.null(base_area_data) && nrow(base_area_data) > 0) {
    p <- p +
      geom_tile(
        data = base_area_data,
        aes(x = F2ppm, y = F1ppm),
        width = f2_resolution,
        height = f1_resolution,
        fill = scales::alpha(base_area_color, base_area_alpha),
        color = base_area_color,
        linewidth = 0.1,
        inherit.aes = FALSE
      )
  }
  
  # Optional: Insert markers and labels for selected signals if `mark_signal` is TRUE and data is provided.
  if (isTRUE(mark_signal) && !is.null(mark_signal_data) && nrow(mark_signal_data) > 0) {
    x_range <- diff(range(sub_spectrum_long$F2ppm))
    x_shift <- x_range * mark_rel_x_shift
    
    p <- p +
      geom_point(
        data = mark_signal_data,
        aes(x = F2ppm, y = F1ppm),
        color = mark_color,
        size = 3,
        shape = 4
      ) +
      geom_label_repel(
        data = mark_signal_data,
        aes(
          x = F2ppm,
          y = F1ppm,
          label = paste(
            "F2[ppm] =", round(F2ppm, 4), "\nF1[ppm] =", round(F1ppm, 4)
          )
        ),
        color = mark_color,
        fill = scales::alpha("white", 0.7),
        direction = "y",
        nudge_x = x_shift,
        hjust = 0,
        box.padding = 0.3,
        point.padding = 0.2,
        max.overlaps = Inf,
        fontface = "bold"
      )
  }

  # Return the ggplot object.
  return(p)
}
